import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Header from "@/components/common/Header";
import {QueryClient, QueryClientProvider} from "react-query";
import TanstackProvider from "@/providers/TanstackProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">

        <body className={inter.className}>{
            <>
                <Header/>
                <TanstackProvider>
                    <div className={"container mx-auto "}>

                        {children}
                    </div>
                </TanstackProvider>
            </>
        }</body>
        </html>
    )
}
